apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
spec:
  provider: azure
  parameters:
    clientID: ${workload_identity}
    keyvaultName: "${key_vault_name}"
    tenantId: "${tenant_id}"
    objects: |
      array:
        - |
          objectName: encryptorsha2dev-crt-pem
          objectType: secret
          objectAlias: encryptorSha2dev.crt.pem
        - |
          objectName: encryptorsha2dev-key-pem
          objectType: secret
          objectAlias: encryptorSha2dev.key.pem 