apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${aks_identity}" # Replace with your UAMI Client ID
    keyvaultName: "${key_vault_name}"
    tenantId: "${tenant_id}"
    objects: |
      array:
        - objectName: "arc4u-net-crt-pem"
          objectType: secret
        - objectName: "arc4u-net-key-pem"
          objectType: secret
  secretObjects:
    - secretName: "encryptor"  # Kubernetes secret name
      type: Opaque
      data:
        - objectName: "arc4u-net-crt-pem"
          key: "encryptorSha2dev.crt.pem"  # Key name in Kubernetes secret
        - objectName: "arc4u-net-key-pem"
          key: "encryptorSha2dev.key.pem"  # Key name in Kubernetes secret