apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "false"
    workloadIdentityClientID: ${aks_identity}
    keyvaultName: "${key_vault_name}"
    tenantId: "${tenant_id}"
    objects: |
      array:
        - |
          objectName: encryptorsha2dev-crt-pem
          objectType: secret